
import React from 'react';
import { ChatMessage } from '../types.ts';
import { GroundingSourcesDisplay } from './GroundingSourcesDisplay.tsx';

interface ChatHistoryProps {
  history: ChatMessage[];
  userTranscript: string;
  jarvisTranscript: string;
}

export const ChatHistory: React.FC<ChatHistoryProps> = ({ history, userTranscript, jarvisTranscript }) => {
  return (
    <div className="w-full max-w-2xl mx-auto space-y-4 text-white p-4 flex-grow overflow-y-auto">
      {history.map((msg, index) => (
        <div key={index} className={`flex items-start gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
          {msg.role === 'jarvis' && <div className="w-8 h-8 rounded-full bg-cyan-500 flex-shrink-0 border-2 border-cyan-300"></div>}
          <div className={`rounded-lg px-4 py-2 max-w-md ${msg.role === 'user' ? 'bg-blue-600' : 'bg-gray-700'}`}>
            {msg.text && <p>{msg.text}</p>}
            {msg.imageUrl && (
              <img src={msg.imageUrl} alt={msg.text || 'Generated by Jarvis'} className="mt-2 rounded-lg max-w-xs sm:max-w-sm border-2 border-gray-600" />
            )}
            {msg.sources && msg.sources.length > 0 && (
              <GroundingSourcesDisplay sources={msg.sources} />
            )}
          </div>
        </div>
      ))}
      {userTranscript && (
        <div className="flex items-start gap-3 justify-end">
          <div className="rounded-lg px-4 py-2 max-w-md bg-blue-600/70 opacity-70">
            <p>{userTranscript}</p>
          </div>
        </div>
      )}
      {jarvisTranscript && (
        <div className="flex items-start gap-3 justify-start">
          <div className="w-8 h-8 rounded-full bg-cyan-500 flex-shrink-0 border-2 border-cyan-300"></div>
          <div className="rounded-lg px-4 py-2 max-w-md bg-gray-700/70 opacity-70">
            <p>{jarvisTranscript}</p>
          </div>
        </div>
      )}
    </div>
  );
};